### ISSUE TITLE
repeated notifications

### ISSUE THREAD

**Issue by kaffeeringe** [pfefferle/wordpress-salmon#2]
Hej, thank you for the whole OStatus collection!

I installed everything today and got the first follower: A guy on Friendika. And I get notified via e-mail every 10 minutes or so. Is that a problem on my side or his?

**Comment by pfefferle** [comment]
No, I also had issues with that, thanks for verifying. I try to figure out the reason.

**Comment by kaffeeringe** [comment]
Can I help somehow?


Am 06.08.2018 22:01 schrieb Matthias Pfefferle <notifications@github.com>:

No, I also had issues with that, thanks for verifying. I try to figure out the reason.

**Comment by pfefferle** [comment]
only if you know what the problem is ;)

...perhaps you can help testing the new version if I find the bug!

**Comment by kaffeeringe** [comment]
Testing I can do ;-)

**Comment by poVoq** [comment]
In general, is there an option to disable these email notifications? 

Edit: It seems I also get repeated notifications after all.

**Comment by petersmithca** [comment]
Also getting these.

**Comment by pfefferle** [comment]
oh sorry, forgot to release the new version!

**Comment by petersmithca** [comment]
Thanks in advance for the release!
