### ISSUE TITLE
Fatal error: Uncaught Error: [] operator not supported for strings

### ISSUE THREAD

**Issue by onliniak** [pfefferle/wordpress-salmon#3]
WordPress 5.0.3
PHP 7.3.1

Fatal error: Uncaught Error: [] operator not supported for strings in /public_html/wp-content/plugins/salmon/salmon.php:116 Stack trace: #0 /public_html/wp-includes/class-wp-hook.php(286): Salmon_Plugin::pre_get_avatar_data(Array, Object(WP_Comment)) #1 /public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /public_html/wp-includes/link-template.php(3873): apply_filters('pre_get_avatar_...', Array, Object(WP_Comment)) #3 public_html/wp-includes/link-template.php(3759): get_avatar_data(Object(WP_Comment), Array) #4 public_html/wp-includes/pluggable.php(2515): get_avatar_url(Object(WP_Comment), Array) #5 public_html/wp-includes/blocks/latest-comments.php(71): get_avatar(Object(WP_Comment), 48, '', '', Array) #6 /public_html/wp- in public_html/wp-content/plugins/salmon/salmon.php on line 116

**Comment by onliniak** [comment]
Strange … It's break only home page (static), not posts. 

Temporary fix: Plugin Organizer → disable on pages.

**Comment by pfefferle** [comment]
oops, thanks for the info... 'will have a look!

**Comment by onliniak** [comment]
I Migrate to ActivityPub. Close.
